# Generated by Django 2.1.7 on 2019-03-27 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190205_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_task_done_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 7, 20, 6, 94128)),
        ),
    ]
