# Generated by Django 2.1.7 on 2019-03-27 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20190327_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='completed_at',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_task_done_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 16, 24, 41, 892867)),
        ),
    ]
