# Generated by Django 2.1.1 on 2019-02-03 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated')),
                ('token', models.CharField(max_length=50)),
                ('last_4_digits', models.CharField(default='1111', max_length=50)),
                ('email', models.EmailField(default='demo', max_length=50)),
                ('name', models.CharField(default='demo', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated')),
                ('messages', models.TextField(max_length=2000)),
                ('txn_id', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=15, null=True, verbose_name='Status')),
                ('_data', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
