# Generated by Django 2.1.1 on 2019-02-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190203_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
