# Generated by Django 2.1.1 on 2019-02-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20190203_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='product',
        ),
    ]
