# Generated by Django 2.1.1 on 2018-12-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0003_auto_20181212_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailytask.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set(),
        ),
    ]
