# Generated by Django 2.1.1 on 2019-01-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0004_auto_20181212_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='video_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='video_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
