# Generated by Django 2.1.7 on 2019-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0005_auto_20190131_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_can_be_repeated',
            field=models.BooleanField(default=False),
        ),
    ]
