# Generated by Django 2.1.7 on 2019-03-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0006_auto_20190327_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
    ]
